agent:
  name: "Telegram Agent"
  id: "telegram-agent-v1"
  description: "An agent that integrates with multiple MCP servers"

strategy:
  type: "conservative"
  max_steps: 10

memory:
  top_k: 5
  type_filter: null

llm:
  model: "gemini-2.0-flash"
  temperature: 0.2
  max_tokens: 1000

persona:
  style: "helpful and concise"
  tone: "professional"

mcp_servers:
  - name: "serpapi"
    script: "serpapi_mcp_server.py"
    cwd: "D:\\AgenticCourse\\Session_8\\serpapi_mcp"
    url: "http://localhost:8050/serpapi_mcp_sse/"
  
  - name: "trafilatura"
    script: "trafilatura_mcp_server.py"
    cwd: "D:\\AgenticCourse\\Session_8\\trafilatura_mcp"
    url: "http://localhost:8030/trafilatura_mcp_sse/"
  
  - name: "gdrive"
    script: "gdrive_mcp_server.py"
    cwd: "D:\\AgenticCourse\\Session_8\\gdrive_mcp"
    url: "http://localhost:8020/gdrive_mcp_sse/"
  
  - name: "telegram"
    script: "telegram_mcp_server.py"
    cwd: "D:\\AgenticCourse\\Session_8\\telegram_mcp"
    url: "http://localhost:8000/telegram_mcp_sse/"
